name: smart_diary
description: >
  مذكرتي الذكية — مذكرة خاصة مدعومة بذكاء اصطناعي محلي.
  خصوصية كاملة، تعمل بلا إنترنت بعد التحميل.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  llamadart: ^0.6.6

  dio: ^5.7.0

  flutter_secure_storage: ^10.0.0

  path_provider: ^2.1.4
  path: ^1.9.0

  encrypt: ^5.0.3
  crypto: ^3.0.3

  shared_preferences: ^2.2.2

  google_fonts: ^8.0.2
  flutter_animate: ^4.5.2

  flutter_markdown: ^0.7.4

  percent_indicator: ^4.2.3

  uuid: ^4.5.1
  intl: ^0.20.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.12

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/unnamed.jpg"
  min_sdk_android: 24
  adaptive_icon_background: "#07070F"
  adaptive_icon_foreground: "assets/unnamed.jpg"
  web:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/unnamed.jpg